# compiler
CC = g++
# flags
FLAGS = -O2 -g3 -std=c++11

all:
	$(CC) src/*.cpp tests/test_grasp.cpp $(FLAGS) -o test_grasp.o

run:
	./test_grasp.o < A-VRP/A-n32-k5.vrp > out/A-n32-k5/A-n32-k5_1.out
	./test_grasp.o < A-VRP/A-n32-k5.vrp > out/A-n32-k5/A-n32-k5_2.out
	./test_grasp.o < A-VRP/A-n32-k5.vrp > out/A-n32-k5/A-n32-k5_3.out
	./test_grasp.o < A-VRP/A-n32-k5.vrp > out/A-n32-k5/A-n32-k5_4.out
	./test_grasp.o < A-VRP/A-n32-k5.vrp > out/A-n32-k5/A-n32-k5_5.out
	./test_grasp.o < A-VRP/A-n32-k5.vrp > out/A-n32-k5/A-n32-k5_6.out
	./test_grasp.o < A-VRP/A-n32-k5.vrp > out/A-n32-k5/A-n32-k5_7.out
	./test_grasp.o < A-VRP/A-n32-k5.vrp > out/A-n32-k5/A-n32-k5_8.out
	./test_grasp.o < A-VRP/A-n32-k5.vrp > out/A-n32-k5/A-n32-k5_9.out
	./test_grasp.o < A-VRP/A-n32-k5.vrp > out/A-n32-k5/A-n32-k5_10.out
	#
	./test_grasp.o < A-VRP/A-n37-k6.vrp > out/A-n37-k6/A-n37-k6_1.out
	./test_grasp.o < A-VRP/A-n37-k6.vrp > out/A-n37-k6/A-n37-k6_2.out
	./test_grasp.o < A-VRP/A-n37-k6.vrp > out/A-n37-k6/A-n37-k6_3.out
	./test_grasp.o < A-VRP/A-n37-k6.vrp > out/A-n37-k6/A-n37-k6_4.out
	./test_grasp.o < A-VRP/A-n37-k6.vrp > out/A-n37-k6/A-n37-k6_5.out
	./test_grasp.o < A-VRP/A-n37-k6.vrp > out/A-n37-k6/A-n37-k6_6.out
	./test_grasp.o < A-VRP/A-n37-k6.vrp > out/A-n37-k6/A-n37-k6_7.out
	./test_grasp.o < A-VRP/A-n37-k6.vrp > out/A-n37-k6/A-n37-k6_8.out
	./test_grasp.o < A-VRP/A-n37-k6.vrp > out/A-n37-k6/A-n37-k6_9.out
	./test_grasp.o < A-VRP/A-n37-k6.vrp > out/A-n37-k6/A-n37-k6_10.out
	#
	./test_grasp.o < A-VRP/A-n44-k7.vrp > out/A-n44-k7/A-n44-k7_1.out
	./test_grasp.o < A-VRP/A-n44-k7.vrp > out/A-n44-k7/A-n44-k7_2.out
	./test_grasp.o < A-VRP/A-n44-k7.vrp > out/A-n44-k7/A-n44-k7_3.out
	./test_grasp.o < A-VRP/A-n44-k7.vrp > out/A-n44-k7/A-n44-k7_4.out
	./test_grasp.o < A-VRP/A-n44-k7.vrp > out/A-n44-k7/A-n44-k7_5.out
	./test_grasp.o < A-VRP/A-n44-k7.vrp > out/A-n44-k7/A-n44-k7_6.out
	./test_grasp.o < A-VRP/A-n44-k7.vrp > out/A-n44-k7/A-n44-k7_7.out
	./test_grasp.o < A-VRP/A-n44-k7.vrp > out/A-n44-k7/A-n44-k7_8.out
	./test_grasp.o < A-VRP/A-n44-k7.vrp > out/A-n44-k7/A-n44-k7_9.out
	./test_grasp.o < A-VRP/A-n44-k7.vrp > out/A-n44-k7/A-n44-k7_10.out
	#
	./test_grasp.o < A-VRP/A-n69-k9.vrp > out/A-n69-k9/A-n69-k9_1.out
	./test_grasp.o < A-VRP/A-n69-k9.vrp > out/A-n69-k9/A-n69-k9_2.out
	./test_grasp.o < A-VRP/A-n69-k9.vrp > out/A-n69-k9/A-n69-k9_3.out
	./test_grasp.o < A-VRP/A-n69-k9.vrp > out/A-n69-k9/A-n69-k9_4.out
	./test_grasp.o < A-VRP/A-n69-k9.vrp > out/A-n69-k9/A-n69-k9_5.out
	./test_grasp.o < A-VRP/A-n69-k9.vrp > out/A-n69-k9/A-n69-k9_6.out
	./test_grasp.o < A-VRP/A-n69-k9.vrp > out/A-n69-k9/A-n69-k9_7.out
	./test_grasp.o < A-VRP/A-n69-k9.vrp > out/A-n69-k9/A-n69-k9_8.out
	./test_grasp.o < A-VRP/A-n69-k9.vrp > out/A-n69-k9/A-n69-k9_9.out
	./test_grasp.o < A-VRP/A-n69-k9.vrp > out/A-n69-k9/A-n69-k9_10.out
	#
	./test_grasp.o < A-VRP/A-n80-k10.vrp > out/A-n80-k10/A-n80-k10_1.out
	./test_grasp.o < A-VRP/A-n80-k10.vrp > out/A-n80-k10/A-n80-k10_2.out
	./test_grasp.o < A-VRP/A-n80-k10.vrp > out/A-n80-k10/A-n80-k10_3.out
	./test_grasp.o < A-VRP/A-n80-k10.vrp > out/A-n80-k10/A-n80-k10_4.out
	./test_grasp.o < A-VRP/A-n80-k10.vrp > out/A-n80-k10/A-n80-k10_5.out
	./test_grasp.o < A-VRP/A-n80-k10.vrp > out/A-n80-k10/A-n80-k10_6.out
	./test_grasp.o < A-VRP/A-n80-k10.vrp > out/A-n80-k10/A-n80-k10_7.out
	./test_grasp.o < A-VRP/A-n80-k10.vrp > out/A-n80-k10/A-n80-k10_8.out
	./test_grasp.o < A-VRP/A-n80-k10.vrp > out/A-n80-k10/A-n80-k10_9.out
	./test_grasp.o < A-VRP/A-n80-k10.vrp > out/A-n80-k10/A-n80-k10_10.out


clean:
	rm vnd
